/**
 * Reads behind the Updates feed: chapters of favourites, newest first.
 *
 * Read-only, so no oplog helper here — nothing in this module changes a row.
 */

import { and, desc, eq, gte, sql } from 'drizzle-orm'
import { decodeTime, encodeTime } from 'ulid'

import { db } from './client'
import { chapters, manga } from './schema'

export interface UpdateEntry {
  chapterId: string
  chapterUrl: string
  chapterName: string
  chapterNumber: number
  dateUpload: number | null
  /** When the row reached this library, decoded from its ULID primary key. */
  addedAt: number
  read: boolean
  lastPageRead: number
  pageCount: number
  downloaded: boolean
  mangaId: string
  sourceId: string
  mangaUrl: string
  mangaTitle: string
  thumbnailUrl: string | null
  mangaMemo: Record<string, unknown> | null
}

export interface UpdateDay {
  /** `YYYY-MM-DD` in local time; a stable list key. */
  key: string
  /** Local midnight of that day, for the heading. */
  date: number
  entries: UpdateEntry[]
}

const DAY_MS = 24 * 60 * 60 * 1000

/** How far back the feed looks by default. */
export const DEFAULT_UPDATE_WINDOW_MS = 30 * DAY_MS

/** Characters of a ULID that hold its timestamp. */
const TIME_LEN = 10

/**
 * Lower bound on `chapters.id` for rows written at or after `ms`.
 *
 * There is no `created_at` column, and `updated_at` moves whenever a chapter is
 * marked read — which would drag chapters you just finished back to the top of
 * the feed. Insertion time therefore comes from the ULID primary key: its first
 * ten characters are the millisecond timestamp in Crockford base32, an encoding
 * that preserves lexicographic order, so both the window filter and the sort
 * are plain string comparisons over the primary key.
 */
function idAtLeast(ms: number): string {
  return encodeTime(Math.max(0, Math.trunc(ms)), TIME_LEN)
}

/** ULIDs are generated by this app, but an imported database may hold anything. */
function addedAtOf(id: string, fallback: number): number {
  try {
    return decodeTime(id)
  } catch {
    return fallback
  }
}

/**
 * Newest first. Scoped to favourites: an update feed is about the library, and
 * every series ever browsed would otherwise drown it.
 */
export async function listRecentChapters(
  limit = 200,
  sinceMs = Date.now() - DEFAULT_UPDATE_WINDOW_MS,
): Promise<UpdateEntry[]> {
  const rows = await db
    .select({
      chapterId: chapters.id,
      chapterUrl: chapters.url,
      chapterName: chapters.name,
      chapterNumber: chapters.chapterNumber,
      dateUpload: chapters.dateUpload,
      updatedAt: chapters.updatedAt,
      read: chapters.read,
      lastPageRead: chapters.lastPageRead,
      pageCount: chapters.pageCount,
      downloaded: chapters.downloaded,
      mangaId: manga.id,
      sourceId: manga.sourceId,
      mangaUrl: manga.url,
      mangaTitle: manga.title,
      thumbnailUrl: manga.thumbnailUrl,
      mangaMemo: manga.memo,
    })
    .from(chapters)
    .innerJoin(manga, eq(manga.id, chapters.mangaId))
    .where(and(eq(manga.favorite, true), gte(chapters.id, idAtLeast(sinceMs))))
    .orderBy(desc(chapters.id))
    .limit(limit)

  return rows.map(({ updatedAt, ...row }) => ({
    ...row,
    addedAt: addedAtOf(row.chapterId, updatedAt),
  }))
}

/**
 * Unread chapters that arrived since `sinceMs` — what "new since your last
 * visit" counts. A chapter already read is not news, however recently it landed.
 */
export async function countUnseenUpdates(
  sinceMs = Date.now() - DEFAULT_UPDATE_WINDOW_MS,
): Promise<number> {
  const [row] = await db
    .select({ count: sql<number>`count(*)` })
    .from(chapters)
    .innerJoin(manga, eq(manga.id, chapters.mangaId))
    .where(
      and(
        eq(manga.favorite, true),
        eq(chapters.read, false),
        gte(chapters.id, idAtLeast(sinceMs)),
      ),
    )
  return row?.count ?? 0
}

/**
 * Buckets an already-sorted feed by the day a chapter arrived.
 *
 * Grouping follows `addedAt` rather than `dateUpload`: the feed answers "what
 * turned up in my library and when", and a source that reports no upload date,
 * or backdates a batch, would otherwise scatter one check across months.
 */
export function groupByDay(entries: readonly UpdateEntry[]): UpdateDay[] {
  const days: UpdateDay[] = []
  let current: UpdateDay | null = null

  for (const entry of entries) {
    const date = startOfDay(entry.addedAt)
    const key = dayKey(date)
    if (!current || current.key !== key) {
      current = { key, date, entries: [] }
      days.push(current)
    }
    current.entries.push(entry)
  }

  return days
}

export interface UpdateSeriesGroup {
  /** The series' id; unique within a day, so a stable list key. */
  key: string
  entries: UpdateEntry[]
}

/**
 * Regroups one day's entries by series, keeping the feed's order.
 *
 * A series takes the position of its newest chapter, which is the first one
 * seen while walking an already newest-first list.
 */
export function groupBySeries(
  entries: readonly UpdateEntry[],
): UpdateSeriesGroup[] {
  const groups = new Map<string, UpdateSeriesGroup>()

  for (const entry of entries) {
    const group = groups.get(entry.mangaId)
    if (group) {
      group.entries.push(entry)
    } else {
      groups.set(entry.mangaId, { key: entry.mangaId, entries: [entry] })
    }
  }

  return [...groups.values()]
}

function startOfDay(timestamp: number): number {
  const date = new Date(timestamp)
  date.setHours(0, 0, 0, 0)
  return date.getTime()
}

function dayKey(midnight: number): string {
  const date = new Date(midnight)
  const month = String(date.getMonth() + 1).padStart(2, '0')
  const day = String(date.getDate()).padStart(2, '0')
  return `${date.getFullYear()}-${month}-${day}`
}
