/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as AsuracdnSplatRouteImport } from './routes/asuracdn.$'
import { Route as AsurascansSplatRouteImport } from './routes/asurascans.$'
import { Route as BrowseIndexRouteImport } from './routes/browse/index'
import { Route as BrowseSourceIdRouteImport } from './routes/browse/$sourceId'
import { Route as ComickSplatRouteImport } from './routes/comick.$'
import { Route as ComickcdnSplatRouteImport } from './routes/comickcdn.$'
import { Route as DownloadsIndexRouteImport } from './routes/downloads/index'
import { Route as FenrirealmSplatRouteImport } from './routes/fenrirealm.$'
import { Route as FlamecdnSplatRouteImport } from './routes/flamecdn.$'
import { Route as FlamecomicsSplatRouteImport } from './routes/flamecomics.$'
import { Route as HistoryIndexRouteImport } from './routes/history/index'
import { Route as KatanacdnSplatRouteImport } from './routes/katanacdn.$'
import { Route as LibraryIndexRouteImport } from './routes/library/index'
import { Route as LibraryCategoriesRouteImport } from './routes/library/categories'
import { Route as MangadexSplatRouteImport } from './routes/mangadex.$'
import { Route as MangadotSplatRouteImport } from './routes/mangadot.$'
import { Route as MangakakalotGraphqlRouteImport } from './routes/mangakakalot.graphql'
import { Route as MangakatanaSplatRouteImport } from './routes/mangakatana.$'
import { Route as MangaplusSplatRouteImport } from './routes/mangaplus.$'
import { Route as MangapluscdnSplatRouteImport } from './routes/mangapluscdn.$'
import { Route as MdcoversSplatRouteImport } from './routes/mdcovers.$'
import { Route as MdimageSplatRouteImport } from './routes/mdimage.$'
import { Route as NovelfullSplatRouteImport } from './routes/novelfull.$'
import { Route as NovelmtlSplatRouteImport } from './routes/novelmtl.$'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as ThunderscansSplatRouteImport } from './routes/thunderscans.$'
import { Route as ToonilySplatRouteImport } from './routes/toonily.$'
import { Route as ToonilycdnSplatRouteImport } from './routes/toonilycdn.$'
import { Route as UpdatesIndexRouteImport } from './routes/updates/index'
import { Route as WebnovelSplatRouteImport } from './routes/webnovel.$'
import { Route as WebtoonsSplatRouteImport } from './routes/webtoons.$'
import { Route as WebtoonscdnSplatRouteImport } from './routes/webtoonscdn.$'
import { Route as WeebcdnSplatRouteImport } from './routes/weebcdn.$'
import { Route as WeebcentralSplatRouteImport } from './routes/weebcentral.$'
import { Route as ApiBillingCheckoutRouteImport } from './routes/api/billing/checkout'
import { Route as ApiBillingPlanRouteImport } from './routes/api/billing/plan'
import { Route as ApiBillingPortalRouteImport } from './routes/api/billing/portal'
import { Route as ApiBillingStatusRouteImport } from './routes/api/billing/status'
import { Route as ApiPolarWebhookRouteImport } from './routes/api/polar/webhook'
import { Route as ApiSyncPullRouteImport } from './routes/api/sync/pull'
import { Route as ApiSyncPushRouteImport } from './routes/api/sync/push'
import { Route as MangaSourceIdSlugRouteImport } from './routes/manga/$sourceId.$slug'
import { Route as ReaderSourceIdSlugChapterRouteImport } from './routes/reader/$sourceId.$slug.$chapter'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const AsuracdnSplatRoute = AsuracdnSplatRouteImport.update({
  id: '/asuracdn/$',
  path: '/asuracdn/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AsurascansSplatRoute = AsurascansSplatRouteImport.update({
  id: '/asurascans/$',
  path: '/asurascans/$',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseIndexRoute = BrowseIndexRouteImport.update({
  id: '/browse/',
  path: '/browse/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseSourceIdRoute = BrowseSourceIdRouteImport.update({
  id: '/browse/$sourceId',
  path: '/browse/$sourceId',
  getParentRoute: () => rootRouteImport,
} as any)
const ComickSplatRoute = ComickSplatRouteImport.update({
  id: '/comick/$',
  path: '/comick/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ComickcdnSplatRoute = ComickcdnSplatRouteImport.update({
  id: '/comickcdn/$',
  path: '/comickcdn/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadsIndexRoute = DownloadsIndexRouteImport.update({
  id: '/downloads/',
  path: '/downloads/',
  getParentRoute: () => rootRouteImport,
} as any)
const FenrirealmSplatRoute = FenrirealmSplatRouteImport.update({
  id: '/fenrirealm/$',
  path: '/fenrirealm/$',
  getParentRoute: () => rootRouteImport,
} as any)
const FlamecdnSplatRoute = FlamecdnSplatRouteImport.update({
  id: '/flamecdn/$',
  path: '/flamecdn/$',
  getParentRoute: () => rootRouteImport,
} as any)
const FlamecomicsSplatRoute = FlamecomicsSplatRouteImport.update({
  id: '/flamecomics/$',
  path: '/flamecomics/$',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryIndexRoute = HistoryIndexRouteImport.update({
  id: '/history/',
  path: '/history/',
  getParentRoute: () => rootRouteImport,
} as any)
const KatanacdnSplatRoute = KatanacdnSplatRouteImport.update({
  id: '/katanacdn/$',
  path: '/katanacdn/$',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryIndexRoute = LibraryIndexRouteImport.update({
  id: '/library/',
  path: '/library/',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryCategoriesRoute = LibraryCategoriesRouteImport.update({
  id: '/library/categories',
  path: '/library/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const MangadexSplatRoute = MangadexSplatRouteImport.update({
  id: '/mangadex/$',
  path: '/mangadex/$',
  getParentRoute: () => rootRouteImport,
} as any)
const MangadotSplatRoute = MangadotSplatRouteImport.update({
  id: '/mangadot/$',
  path: '/mangadot/$',
  getParentRoute: () => rootRouteImport,
} as any)
const MangakakalotGraphqlRoute = MangakakalotGraphqlRouteImport.update({
  id: '/mangakakalot/graphql',
  path: '/mangakakalot/graphql',
  getParentRoute: () => rootRouteImport,
} as any)
const MangakatanaSplatRoute = MangakatanaSplatRouteImport.update({
  id: '/mangakatana/$',
  path: '/mangakatana/$',
  getParentRoute: () => rootRouteImport,
} as any)
const MangaplusSplatRoute = MangaplusSplatRouteImport.update({
  id: '/mangaplus/$',
  path: '/mangaplus/$',
  getParentRoute: () => rootRouteImport,
} as any)
const MangapluscdnSplatRoute = MangapluscdnSplatRouteImport.update({
  id: '/mangapluscdn/$',
  path: '/mangapluscdn/$',
  getParentRoute: () => rootRouteImport,
} as any)
const MdcoversSplatRoute = MdcoversSplatRouteImport.update({
  id: '/mdcovers/$',
  path: '/mdcovers/$',
  getParentRoute: () => rootRouteImport,
} as any)
const MdimageSplatRoute = MdimageSplatRouteImport.update({
  id: '/mdimage/$',
  path: '/mdimage/$',
  getParentRoute: () => rootRouteImport,
} as any)
const NovelfullSplatRoute = NovelfullSplatRouteImport.update({
  id: '/novelfull/$',
  path: '/novelfull/$',
  getParentRoute: () => rootRouteImport,
} as any)
const NovelmtlSplatRoute = NovelmtlSplatRouteImport.update({
  id: '/novelmtl/$',
  path: '/novelmtl/$',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const ThunderscansSplatRoute = ThunderscansSplatRouteImport.update({
  id: '/thunderscans/$',
  path: '/thunderscans/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ToonilySplatRoute = ToonilySplatRouteImport.update({
  id: '/toonily/$',
  path: '/toonily/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ToonilycdnSplatRoute = ToonilycdnSplatRouteImport.update({
  id: '/toonilycdn/$',
  path: '/toonilycdn/$',
  getParentRoute: () => rootRouteImport,
} as any)
const UpdatesIndexRoute = UpdatesIndexRouteImport.update({
  id: '/updates/',
  path: '/updates/',
  getParentRoute: () => rootRouteImport,
} as any)
const WebnovelSplatRoute = WebnovelSplatRouteImport.update({
  id: '/webnovel/$',
  path: '/webnovel/$',
  getParentRoute: () => rootRouteImport,
} as any)
const WebtoonsSplatRoute = WebtoonsSplatRouteImport.update({
  id: '/webtoons/$',
  path: '/webtoons/$',
  getParentRoute: () => rootRouteImport,
} as any)
const WebtoonscdnSplatRoute = WebtoonscdnSplatRouteImport.update({
  id: '/webtoonscdn/$',
  path: '/webtoonscdn/$',
  getParentRoute: () => rootRouteImport,
} as any)
const WeebcdnSplatRoute = WeebcdnSplatRouteImport.update({
  id: '/weebcdn/$',
  path: '/weebcdn/$',
  getParentRoute: () => rootRouteImport,
} as any)
const WeebcentralSplatRoute = WeebcentralSplatRouteImport.update({
  id: '/weebcentral/$',
  path: '/weebcentral/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBillingCheckoutRoute = ApiBillingCheckoutRouteImport.update({
  id: '/api/billing/checkout',
  path: '/api/billing/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBillingPlanRoute = ApiBillingPlanRouteImport.update({
  id: '/api/billing/plan',
  path: '/api/billing/plan',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBillingPortalRoute = ApiBillingPortalRouteImport.update({
  id: '/api/billing/portal',
  path: '/api/billing/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBillingStatusRoute = ApiBillingStatusRouteImport.update({
  id: '/api/billing/status',
  path: '/api/billing/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPolarWebhookRoute = ApiPolarWebhookRouteImport.update({
  id: '/api/polar/webhook',
  path: '/api/polar/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSyncPullRoute = ApiSyncPullRouteImport.update({
  id: '/api/sync/pull',
  path: '/api/sync/pull',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSyncPushRoute = ApiSyncPushRouteImport.update({
  id: '/api/sync/push',
  path: '/api/sync/push',
  getParentRoute: () => rootRouteImport,
} as any)
const MangaSourceIdSlugRoute = MangaSourceIdSlugRouteImport.update({
  id: '/manga/$sourceId/$slug',
  path: '/manga/$sourceId/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ReaderSourceIdSlugChapterRoute =
  ReaderSourceIdSlugChapterRouteImport.update({
    id: '/reader/$sourceId/$slug/$chapter',
    path: '/reader/$sourceId/$slug/$chapter',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/welcome': typeof WelcomeRoute
  '/asuracdn/$': typeof AsuracdnSplatRoute
  '/asurascans/$': typeof AsurascansSplatRoute
  '/browse/$sourceId': typeof BrowseSourceIdRoute
  '/comick/$': typeof ComickSplatRoute
  '/comickcdn/$': typeof ComickcdnSplatRoute
  '/fenrirealm/$': typeof FenrirealmSplatRoute
  '/flamecdn/$': typeof FlamecdnSplatRoute
  '/flamecomics/$': typeof FlamecomicsSplatRoute
  '/katanacdn/$': typeof KatanacdnSplatRoute
  '/library/categories': typeof LibraryCategoriesRoute
  '/mangadex/$': typeof MangadexSplatRoute
  '/mangadot/$': typeof MangadotSplatRoute
  '/mangakakalot/graphql': typeof MangakakalotGraphqlRoute
  '/mangakatana/$': typeof MangakatanaSplatRoute
  '/mangaplus/$': typeof MangaplusSplatRoute
  '/mangapluscdn/$': typeof MangapluscdnSplatRoute
  '/mdcovers/$': typeof MdcoversSplatRoute
  '/mdimage/$': typeof MdimageSplatRoute
  '/novelfull/$': typeof NovelfullSplatRoute
  '/novelmtl/$': typeof NovelmtlSplatRoute
  '/thunderscans/$': typeof ThunderscansSplatRoute
  '/toonily/$': typeof ToonilySplatRoute
  '/toonilycdn/$': typeof ToonilycdnSplatRoute
  '/webnovel/$': typeof WebnovelSplatRoute
  '/webtoons/$': typeof WebtoonsSplatRoute
  '/webtoonscdn/$': typeof WebtoonscdnSplatRoute
  '/weebcdn/$': typeof WeebcdnSplatRoute
  '/weebcentral/$': typeof WeebcentralSplatRoute
  '/browse/': typeof BrowseIndexRoute
  '/downloads/': typeof DownloadsIndexRoute
  '/history/': typeof HistoryIndexRoute
  '/library/': typeof LibraryIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/updates/': typeof UpdatesIndexRoute
  '/api/billing/checkout': typeof ApiBillingCheckoutRoute
  '/api/billing/plan': typeof ApiBillingPlanRoute
  '/api/billing/portal': typeof ApiBillingPortalRoute
  '/api/billing/status': typeof ApiBillingStatusRoute
  '/api/polar/webhook': typeof ApiPolarWebhookRoute
  '/api/sync/pull': typeof ApiSyncPullRoute
  '/api/sync/push': typeof ApiSyncPushRoute
  '/manga/$sourceId/$slug': typeof MangaSourceIdSlugRoute
  '/reader/$sourceId/$slug/$chapter': typeof ReaderSourceIdSlugChapterRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/welcome': typeof WelcomeRoute
  '/asuracdn/$': typeof AsuracdnSplatRoute
  '/asurascans/$': typeof AsurascansSplatRoute
  '/browse/$sourceId': typeof BrowseSourceIdRoute
  '/comick/$': typeof ComickSplatRoute
  '/comickcdn/$': typeof ComickcdnSplatRoute
  '/fenrirealm/$': typeof FenrirealmSplatRoute
  '/flamecdn/$': typeof FlamecdnSplatRoute
  '/flamecomics/$': typeof FlamecomicsSplatRoute
  '/katanacdn/$': typeof KatanacdnSplatRoute
  '/library/categories': typeof LibraryCategoriesRoute
  '/mangadex/$': typeof MangadexSplatRoute
  '/mangadot/$': typeof MangadotSplatRoute
  '/mangakakalot/graphql': typeof MangakakalotGraphqlRoute
  '/mangakatana/$': typeof MangakatanaSplatRoute
  '/mangaplus/$': typeof MangaplusSplatRoute
  '/mangapluscdn/$': typeof MangapluscdnSplatRoute
  '/mdcovers/$': typeof MdcoversSplatRoute
  '/mdimage/$': typeof MdimageSplatRoute
  '/novelfull/$': typeof NovelfullSplatRoute
  '/novelmtl/$': typeof NovelmtlSplatRoute
  '/thunderscans/$': typeof ThunderscansSplatRoute
  '/toonily/$': typeof ToonilySplatRoute
  '/toonilycdn/$': typeof ToonilycdnSplatRoute
  '/webnovel/$': typeof WebnovelSplatRoute
  '/webtoons/$': typeof WebtoonsSplatRoute
  '/webtoonscdn/$': typeof WebtoonscdnSplatRoute
  '/weebcdn/$': typeof WeebcdnSplatRoute
  '/weebcentral/$': typeof WeebcentralSplatRoute
  '/browse': typeof BrowseIndexRoute
  '/downloads': typeof DownloadsIndexRoute
  '/history': typeof HistoryIndexRoute
  '/library': typeof LibraryIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/updates': typeof UpdatesIndexRoute
  '/api/billing/checkout': typeof ApiBillingCheckoutRoute
  '/api/billing/plan': typeof ApiBillingPlanRoute
  '/api/billing/portal': typeof ApiBillingPortalRoute
  '/api/billing/status': typeof ApiBillingStatusRoute
  '/api/polar/webhook': typeof ApiPolarWebhookRoute
  '/api/sync/pull': typeof ApiSyncPullRoute
  '/api/sync/push': typeof ApiSyncPushRoute
  '/manga/$sourceId/$slug': typeof MangaSourceIdSlugRoute
  '/reader/$sourceId/$slug/$chapter': typeof ReaderSourceIdSlugChapterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/welcome': typeof WelcomeRoute
  '/asuracdn/$': typeof AsuracdnSplatRoute
  '/asurascans/$': typeof AsurascansSplatRoute
  '/browse/$sourceId': typeof BrowseSourceIdRoute
  '/comick/$': typeof ComickSplatRoute
  '/comickcdn/$': typeof ComickcdnSplatRoute
  '/fenrirealm/$': typeof FenrirealmSplatRoute
  '/flamecdn/$': typeof FlamecdnSplatRoute
  '/flamecomics/$': typeof FlamecomicsSplatRoute
  '/katanacdn/$': typeof KatanacdnSplatRoute
  '/library/categories': typeof LibraryCategoriesRoute
  '/mangadex/$': typeof MangadexSplatRoute
  '/mangadot/$': typeof MangadotSplatRoute
  '/mangakakalot/graphql': typeof MangakakalotGraphqlRoute
  '/mangakatana/$': typeof MangakatanaSplatRoute
  '/mangaplus/$': typeof MangaplusSplatRoute
  '/mangapluscdn/$': typeof MangapluscdnSplatRoute
  '/mdcovers/$': typeof MdcoversSplatRoute
  '/mdimage/$': typeof MdimageSplatRoute
  '/novelfull/$': typeof NovelfullSplatRoute
  '/novelmtl/$': typeof NovelmtlSplatRoute
  '/thunderscans/$': typeof ThunderscansSplatRoute
  '/toonily/$': typeof ToonilySplatRoute
  '/toonilycdn/$': typeof ToonilycdnSplatRoute
  '/webnovel/$': typeof WebnovelSplatRoute
  '/webtoons/$': typeof WebtoonsSplatRoute
  '/webtoonscdn/$': typeof WebtoonscdnSplatRoute
  '/weebcdn/$': typeof WeebcdnSplatRoute
  '/weebcentral/$': typeof WeebcentralSplatRoute
  '/browse/': typeof BrowseIndexRoute
  '/downloads/': typeof DownloadsIndexRoute
  '/history/': typeof HistoryIndexRoute
  '/library/': typeof LibraryIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/updates/': typeof UpdatesIndexRoute
  '/api/billing/checkout': typeof ApiBillingCheckoutRoute
  '/api/billing/plan': typeof ApiBillingPlanRoute
  '/api/billing/portal': typeof ApiBillingPortalRoute
  '/api/billing/status': typeof ApiBillingStatusRoute
  '/api/polar/webhook': typeof ApiPolarWebhookRoute
  '/api/sync/pull': typeof ApiSyncPullRoute
  '/api/sync/push': typeof ApiSyncPushRoute
  '/manga/$sourceId/$slug': typeof MangaSourceIdSlugRoute
  '/reader/$sourceId/$slug/$chapter': typeof ReaderSourceIdSlugChapterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/welcome'
    | '/asuracdn/$'
    | '/asurascans/$'
    | '/browse/$sourceId'
    | '/comick/$'
    | '/comickcdn/$'
    | '/fenrirealm/$'
    | '/flamecdn/$'
    | '/flamecomics/$'
    | '/katanacdn/$'
    | '/library/categories'
    | '/mangadex/$'
    | '/mangadot/$'
    | '/mangakakalot/graphql'
    | '/mangakatana/$'
    | '/mangaplus/$'
    | '/mangapluscdn/$'
    | '/mdcovers/$'
    | '/mdimage/$'
    | '/novelfull/$'
    | '/novelmtl/$'
    | '/thunderscans/$'
    | '/toonily/$'
    | '/toonilycdn/$'
    | '/webnovel/$'
    | '/webtoons/$'
    | '/webtoonscdn/$'
    | '/weebcdn/$'
    | '/weebcentral/$'
    | '/browse/'
    | '/downloads/'
    | '/history/'
    | '/library/'
    | '/settings/'
    | '/updates/'
    | '/api/billing/checkout'
    | '/api/billing/plan'
    | '/api/billing/portal'
    | '/api/billing/status'
    | '/api/polar/webhook'
    | '/api/sync/pull'
    | '/api/sync/push'
    | '/manga/$sourceId/$slug'
    | '/reader/$sourceId/$slug/$chapter'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/welcome'
    | '/asuracdn/$'
    | '/asurascans/$'
    | '/browse/$sourceId'
    | '/comick/$'
    | '/comickcdn/$'
    | '/fenrirealm/$'
    | '/flamecdn/$'
    | '/flamecomics/$'
    | '/katanacdn/$'
    | '/library/categories'
    | '/mangadex/$'
    | '/mangadot/$'
    | '/mangakakalot/graphql'
    | '/mangakatana/$'
    | '/mangaplus/$'
    | '/mangapluscdn/$'
    | '/mdcovers/$'
    | '/mdimage/$'
    | '/novelfull/$'
    | '/novelmtl/$'
    | '/thunderscans/$'
    | '/toonily/$'
    | '/toonilycdn/$'
    | '/webnovel/$'
    | '/webtoons/$'
    | '/webtoonscdn/$'
    | '/weebcdn/$'
    | '/weebcentral/$'
    | '/browse'
    | '/downloads'
    | '/history'
    | '/library'
    | '/settings'
    | '/updates'
    | '/api/billing/checkout'
    | '/api/billing/plan'
    | '/api/billing/portal'
    | '/api/billing/status'
    | '/api/polar/webhook'
    | '/api/sync/pull'
    | '/api/sync/push'
    | '/manga/$sourceId/$slug'
    | '/reader/$sourceId/$slug/$chapter'
  id:
    | '__root__'
    | '/'
    | '/welcome'
    | '/asuracdn/$'
    | '/asurascans/$'
    | '/browse/$sourceId'
    | '/comick/$'
    | '/comickcdn/$'
    | '/fenrirealm/$'
    | '/flamecdn/$'
    | '/flamecomics/$'
    | '/katanacdn/$'
    | '/library/categories'
    | '/mangadex/$'
    | '/mangadot/$'
    | '/mangakakalot/graphql'
    | '/mangakatana/$'
    | '/mangaplus/$'
    | '/mangapluscdn/$'
    | '/mdcovers/$'
    | '/mdimage/$'
    | '/novelfull/$'
    | '/novelmtl/$'
    | '/thunderscans/$'
    | '/toonily/$'
    | '/toonilycdn/$'
    | '/webnovel/$'
    | '/webtoons/$'
    | '/webtoonscdn/$'
    | '/weebcdn/$'
    | '/weebcentral/$'
    | '/browse/'
    | '/downloads/'
    | '/history/'
    | '/library/'
    | '/settings/'
    | '/updates/'
    | '/api/billing/checkout'
    | '/api/billing/plan'
    | '/api/billing/portal'
    | '/api/billing/status'
    | '/api/polar/webhook'
    | '/api/sync/pull'
    | '/api/sync/push'
    | '/manga/$sourceId/$slug'
    | '/reader/$sourceId/$slug/$chapter'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WelcomeRoute: typeof WelcomeRoute
  AsuracdnSplatRoute: typeof AsuracdnSplatRoute
  AsurascansSplatRoute: typeof AsurascansSplatRoute
  BrowseSourceIdRoute: typeof BrowseSourceIdRoute
  ComickSplatRoute: typeof ComickSplatRoute
  ComickcdnSplatRoute: typeof ComickcdnSplatRoute
  FenrirealmSplatRoute: typeof FenrirealmSplatRoute
  FlamecdnSplatRoute: typeof FlamecdnSplatRoute
  FlamecomicsSplatRoute: typeof FlamecomicsSplatRoute
  KatanacdnSplatRoute: typeof KatanacdnSplatRoute
  LibraryCategoriesRoute: typeof LibraryCategoriesRoute
  MangadexSplatRoute: typeof MangadexSplatRoute
  MangadotSplatRoute: typeof MangadotSplatRoute
  MangakakalotGraphqlRoute: typeof MangakakalotGraphqlRoute
  MangakatanaSplatRoute: typeof MangakatanaSplatRoute
  MangaplusSplatRoute: typeof MangaplusSplatRoute
  MangapluscdnSplatRoute: typeof MangapluscdnSplatRoute
  MdcoversSplatRoute: typeof MdcoversSplatRoute
  MdimageSplatRoute: typeof MdimageSplatRoute
  NovelfullSplatRoute: typeof NovelfullSplatRoute
  NovelmtlSplatRoute: typeof NovelmtlSplatRoute
  ThunderscansSplatRoute: typeof ThunderscansSplatRoute
  ToonilySplatRoute: typeof ToonilySplatRoute
  ToonilycdnSplatRoute: typeof ToonilycdnSplatRoute
  WebnovelSplatRoute: typeof WebnovelSplatRoute
  WebtoonsSplatRoute: typeof WebtoonsSplatRoute
  WebtoonscdnSplatRoute: typeof WebtoonscdnSplatRoute
  WeebcdnSplatRoute: typeof WeebcdnSplatRoute
  WeebcentralSplatRoute: typeof WeebcentralSplatRoute
  BrowseIndexRoute: typeof BrowseIndexRoute
  DownloadsIndexRoute: typeof DownloadsIndexRoute
  HistoryIndexRoute: typeof HistoryIndexRoute
  LibraryIndexRoute: typeof LibraryIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  UpdatesIndexRoute: typeof UpdatesIndexRoute
  ApiBillingCheckoutRoute: typeof ApiBillingCheckoutRoute
  ApiBillingPlanRoute: typeof ApiBillingPlanRoute
  ApiBillingPortalRoute: typeof ApiBillingPortalRoute
  ApiBillingStatusRoute: typeof ApiBillingStatusRoute
  ApiPolarWebhookRoute: typeof ApiPolarWebhookRoute
  ApiSyncPullRoute: typeof ApiSyncPullRoute
  ApiSyncPushRoute: typeof ApiSyncPushRoute
  MangaSourceIdSlugRoute: typeof MangaSourceIdSlugRoute
  ReaderSourceIdSlugChapterRoute: typeof ReaderSourceIdSlugChapterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/asuracdn/$': {
      id: '/asuracdn/$'
      path: '/asuracdn/$'
      fullPath: '/asuracdn/$'
      preLoaderRoute: typeof AsuracdnSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/asurascans/$': {
      id: '/asurascans/$'
      path: '/asurascans/$'
      fullPath: '/asurascans/$'
      preLoaderRoute: typeof AsurascansSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse/': {
      id: '/browse/'
      path: '/browse'
      fullPath: '/browse/'
      preLoaderRoute: typeof BrowseIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse/$sourceId': {
      id: '/browse/$sourceId'
      path: '/browse/$sourceId'
      fullPath: '/browse/$sourceId'
      preLoaderRoute: typeof BrowseSourceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comick/$': {
      id: '/comick/$'
      path: '/comick/$'
      fullPath: '/comick/$'
      preLoaderRoute: typeof ComickSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comickcdn/$': {
      id: '/comickcdn/$'
      path: '/comickcdn/$'
      fullPath: '/comickcdn/$'
      preLoaderRoute: typeof ComickcdnSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/downloads/': {
      id: '/downloads/'
      path: '/downloads'
      fullPath: '/downloads/'
      preLoaderRoute: typeof DownloadsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fenrirealm/$': {
      id: '/fenrirealm/$'
      path: '/fenrirealm/$'
      fullPath: '/fenrirealm/$'
      preLoaderRoute: typeof FenrirealmSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flamecdn/$': {
      id: '/flamecdn/$'
      path: '/flamecdn/$'
      fullPath: '/flamecdn/$'
      preLoaderRoute: typeof FlamecdnSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flamecomics/$': {
      id: '/flamecomics/$'
      path: '/flamecomics/$'
      fullPath: '/flamecomics/$'
      preLoaderRoute: typeof FlamecomicsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history/': {
      id: '/history/'
      path: '/history'
      fullPath: '/history/'
      preLoaderRoute: typeof HistoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/katanacdn/$': {
      id: '/katanacdn/$'
      path: '/katanacdn/$'
      fullPath: '/katanacdn/$'
      preLoaderRoute: typeof KatanacdnSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/': {
      id: '/library/'
      path: '/library'
      fullPath: '/library/'
      preLoaderRoute: typeof LibraryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/categories': {
      id: '/library/categories'
      path: '/library/categories'
      fullPath: '/library/categories'
      preLoaderRoute: typeof LibraryCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mangadex/$': {
      id: '/mangadex/$'
      path: '/mangadex/$'
      fullPath: '/mangadex/$'
      preLoaderRoute: typeof MangadexSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mangadot/$': {
      id: '/mangadot/$'
      path: '/mangadot/$'
      fullPath: '/mangadot/$'
      preLoaderRoute: typeof MangadotSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mangakakalot/graphql': {
      id: '/mangakakalot/graphql'
      path: '/mangakakalot/graphql'
      fullPath: '/mangakakalot/graphql'
      preLoaderRoute: typeof MangakakalotGraphqlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mangakatana/$': {
      id: '/mangakatana/$'
      path: '/mangakatana/$'
      fullPath: '/mangakatana/$'
      preLoaderRoute: typeof MangakatanaSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mangaplus/$': {
      id: '/mangaplus/$'
      path: '/mangaplus/$'
      fullPath: '/mangaplus/$'
      preLoaderRoute: typeof MangaplusSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mangapluscdn/$': {
      id: '/mangapluscdn/$'
      path: '/mangapluscdn/$'
      fullPath: '/mangapluscdn/$'
      preLoaderRoute: typeof MangapluscdnSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mdcovers/$': {
      id: '/mdcovers/$'
      path: '/mdcovers/$'
      fullPath: '/mdcovers/$'
      preLoaderRoute: typeof MdcoversSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mdimage/$': {
      id: '/mdimage/$'
      path: '/mdimage/$'
      fullPath: '/mdimage/$'
      preLoaderRoute: typeof MdimageSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/novelfull/$': {
      id: '/novelfull/$'
      path: '/novelfull/$'
      fullPath: '/novelfull/$'
      preLoaderRoute: typeof NovelfullSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/novelmtl/$': {
      id: '/novelmtl/$'
      path: '/novelmtl/$'
      fullPath: '/novelmtl/$'
      preLoaderRoute: typeof NovelmtlSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thunderscans/$': {
      id: '/thunderscans/$'
      path: '/thunderscans/$'
      fullPath: '/thunderscans/$'
      preLoaderRoute: typeof ThunderscansSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/toonily/$': {
      id: '/toonily/$'
      path: '/toonily/$'
      fullPath: '/toonily/$'
      preLoaderRoute: typeof ToonilySplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/toonilycdn/$': {
      id: '/toonilycdn/$'
      path: '/toonilycdn/$'
      fullPath: '/toonilycdn/$'
      preLoaderRoute: typeof ToonilycdnSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/updates/': {
      id: '/updates/'
      path: '/updates'
      fullPath: '/updates/'
      preLoaderRoute: typeof UpdatesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/webnovel/$': {
      id: '/webnovel/$'
      path: '/webnovel/$'
      fullPath: '/webnovel/$'
      preLoaderRoute: typeof WebnovelSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/webtoons/$': {
      id: '/webtoons/$'
      path: '/webtoons/$'
      fullPath: '/webtoons/$'
      preLoaderRoute: typeof WebtoonsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/webtoonscdn/$': {
      id: '/webtoonscdn/$'
      path: '/webtoonscdn/$'
      fullPath: '/webtoonscdn/$'
      preLoaderRoute: typeof WebtoonscdnSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/weebcdn/$': {
      id: '/weebcdn/$'
      path: '/weebcdn/$'
      fullPath: '/weebcdn/$'
      preLoaderRoute: typeof WeebcdnSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/weebcentral/$': {
      id: '/weebcentral/$'
      path: '/weebcentral/$'
      fullPath: '/weebcentral/$'
      preLoaderRoute: typeof WeebcentralSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing/checkout': {
      id: '/api/billing/checkout'
      path: '/api/billing/checkout'
      fullPath: '/api/billing/checkout'
      preLoaderRoute: typeof ApiBillingCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing/plan': {
      id: '/api/billing/plan'
      path: '/api/billing/plan'
      fullPath: '/api/billing/plan'
      preLoaderRoute: typeof ApiBillingPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing/portal': {
      id: '/api/billing/portal'
      path: '/api/billing/portal'
      fullPath: '/api/billing/portal'
      preLoaderRoute: typeof ApiBillingPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing/status': {
      id: '/api/billing/status'
      path: '/api/billing/status'
      fullPath: '/api/billing/status'
      preLoaderRoute: typeof ApiBillingStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/polar/webhook': {
      id: '/api/polar/webhook'
      path: '/api/polar/webhook'
      fullPath: '/api/polar/webhook'
      preLoaderRoute: typeof ApiPolarWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sync/pull': {
      id: '/api/sync/pull'
      path: '/api/sync/pull'
      fullPath: '/api/sync/pull'
      preLoaderRoute: typeof ApiSyncPullRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sync/push': {
      id: '/api/sync/push'
      path: '/api/sync/push'
      fullPath: '/api/sync/push'
      preLoaderRoute: typeof ApiSyncPushRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manga/$sourceId/$slug': {
      id: '/manga/$sourceId/$slug'
      path: '/manga/$sourceId/$slug'
      fullPath: '/manga/$sourceId/$slug'
      preLoaderRoute: typeof MangaSourceIdSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reader/$sourceId/$slug/$chapter': {
      id: '/reader/$sourceId/$slug/$chapter'
      path: '/reader/$sourceId/$slug/$chapter'
      fullPath: '/reader/$sourceId/$slug/$chapter'
      preLoaderRoute: typeof ReaderSourceIdSlugChapterRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WelcomeRoute: WelcomeRoute,
  AsuracdnSplatRoute: AsuracdnSplatRoute,
  AsurascansSplatRoute: AsurascansSplatRoute,
  BrowseSourceIdRoute: BrowseSourceIdRoute,
  ComickSplatRoute: ComickSplatRoute,
  ComickcdnSplatRoute: ComickcdnSplatRoute,
  FenrirealmSplatRoute: FenrirealmSplatRoute,
  FlamecdnSplatRoute: FlamecdnSplatRoute,
  FlamecomicsSplatRoute: FlamecomicsSplatRoute,
  KatanacdnSplatRoute: KatanacdnSplatRoute,
  LibraryCategoriesRoute: LibraryCategoriesRoute,
  MangadexSplatRoute: MangadexSplatRoute,
  MangadotSplatRoute: MangadotSplatRoute,
  MangakakalotGraphqlRoute: MangakakalotGraphqlRoute,
  MangakatanaSplatRoute: MangakatanaSplatRoute,
  MangaplusSplatRoute: MangaplusSplatRoute,
  MangapluscdnSplatRoute: MangapluscdnSplatRoute,
  MdcoversSplatRoute: MdcoversSplatRoute,
  MdimageSplatRoute: MdimageSplatRoute,
  NovelfullSplatRoute: NovelfullSplatRoute,
  NovelmtlSplatRoute: NovelmtlSplatRoute,
  ThunderscansSplatRoute: ThunderscansSplatRoute,
  ToonilySplatRoute: ToonilySplatRoute,
  ToonilycdnSplatRoute: ToonilycdnSplatRoute,
  WebnovelSplatRoute: WebnovelSplatRoute,
  WebtoonsSplatRoute: WebtoonsSplatRoute,
  WebtoonscdnSplatRoute: WebtoonscdnSplatRoute,
  WeebcdnSplatRoute: WeebcdnSplatRoute,
  WeebcentralSplatRoute: WeebcentralSplatRoute,
  BrowseIndexRoute: BrowseIndexRoute,
  DownloadsIndexRoute: DownloadsIndexRoute,
  HistoryIndexRoute: HistoryIndexRoute,
  LibraryIndexRoute: LibraryIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  UpdatesIndexRoute: UpdatesIndexRoute,
  ApiBillingCheckoutRoute: ApiBillingCheckoutRoute,
  ApiBillingPlanRoute: ApiBillingPlanRoute,
  ApiBillingPortalRoute: ApiBillingPortalRoute,
  ApiBillingStatusRoute: ApiBillingStatusRoute,
  ApiPolarWebhookRoute: ApiPolarWebhookRoute,
  ApiSyncPullRoute: ApiSyncPullRoute,
  ApiSyncPushRoute: ApiSyncPushRoute,
  MangaSourceIdSlugRoute: MangaSourceIdSlugRoute,
  ReaderSourceIdSlugChapterRoute: ReaderSourceIdSlugChapterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
